twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/assets/styles': styles
        '%kernel.project_dir%/assets/images': images
    globals:
        recaptcha_key: '%env(RECAPTCHA3_KEY)%'

when@test:
    twig:
        strict_variables: true
